# Generated by Django 5.2.7 on 2025-10-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('empresa_fornecedora', models.CharField(max_length=100)),
                ('data_validade_contrato', models.DateField()),
                ('status_conformidade', models.CharField(default='Em Análise', max_length=50)),
            ],
        ),
    ]
